stages:
  - lint
  - docs
  - frontend_build
  - backend_build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - frontend/.npm/
    - .cache/pip

eslint:
  stage: lint
  image: node:latest
  needs: []
  script:
    - node --version
    - npm --version
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npx eslint --format=junit src > ../eslint.xml || exit 0
  artifacts:
    reports:
      junit: eslint.xml

pylint:
  stage: lint
  image: python:latest
  needs: []
  script:
    - apt-get update
    - apt-get install -y gcc libldap-common libldap2-dev libsasl2-dev
    - cd backend
    - pip3 install poetry
    - poetry config virtualenvs.create false
    - poetry install
    - pylint --exit-zero --output-format=junit shrunk tests/*.py > pylint.xml
  artifacts:
    reports:
      junit: backend/pylint.xml

mypy:
  stage: lint
  image: python:latest
  needs: []
  script:
    - cd backend
    - pip3 install poetry
    - poetry config virtualenvs.create false
    - poetry install
    - mypy --junit-xml=./mypy.xml backend/shrunk backend/tests || exit 0
  artifacts:
    reports:
      junit: mypy.xml

flake8:
  stage: lint
  image: python:latest
  needs: []
  script:
    - cd backend
    - pip3 install poetry
    - poetry config virtualenvs.create false
    - poetry install
    - flake8 --format=pylint --config=pyproject.toml --exit-zero --format=junit-xml shrunk backend/tests > flake8.xml
  artifacts:
    reports:
      junit: backend/flake8.xml

typedoc:
  stage: docs
  image: node:latest
  needs: []
  script:
    - node --version
    - npm --version
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npm run doc
  artifacts:
    paths:
      - frontend/docs

frontend_build:
  stage: frontend_build
  image: node:latest
  needs: []
  script:
    - node --version
    - npm --version
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - frontend/dist/*

backend_build:
  stage: backend_build
  image: python:latest
  needs:
    - frontend_build
  script:
    - cd backend
    - pip3 install poetry
    - poetry config virtualenvs.create false
    - poetry install
    - mkdir backend/shrunk/static/dist
    - rm -f backend/shrunk/static/dist/index.html backend/shrunk/templates/index.html
    - python3 -m poetry build
  artifacts:
    paths:
      - backend/dist/shrunk-*.whl

pytest:
  stage: test
  image: centos:centos7
  needs:
    - backend_build
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip_centos"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip_centos
  services:
    - mongo
  script:
    - yum install -y gcc python3-pip python3-devel openldap-devel
    - cd backend
    - pip3 install poetry
    - poetry config virtualenvs.create false
    - poetry install
    - poetry build
    - pip3 install backend/dist/shrunk-*.whl
    - export SHRUNK_CONFIG_PATH=$(pwd)/backend/shrunk/ci-test-config.py
    - mkdir /usr/share/GeoIP
    - cp backend/GeoLite2-City.mmdb /usr/share/GeoIP/GeoLite2-City.mmdb
    - cd backend
    - echo "GOOGLE_SAFE_BROWSING_API = '$GOOGLE_SAFE_BROWSING_API'" >> ./shrunk/ci-test-config.py
    - pytest --junitxml=../pytest.xml tests
  artifacts:
    reports:
      junit: pytest.xml
