stages:
  - lint
  - build
  - test
  - promote

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - frontend/.npm/
    - .cache/pip

.images:
  parallel:
    matrix:
      - IMAGE: ["frontend", "backend", "shib-sp"]

.buildah:
  image: quay.io/buildah/stable
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_ISOLATION: chroot
  before_script:
    - buildah login -u "$CI_REGISTRY_USER" --password $CI_REGISTRY_PASSWORD $CI_REGISTRY

.skopeo:
  image:
    name: quay.io/skopeo/stable
    entrypoint: [""]
  stage: promote
  before_script:
    - skopeo login -u "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

.mongo-service:
  services:
    - &mongo_service
      name: mongo:7
      alias: mongo
      command:
        - sh
        - -c
        - |
          replicaset() {
            while ! mongosh --eval 'db.version()' >/dev/null 2>/dev/null; do
              echo "mongo not ready... waiting..."
              sleep 1
            done
            echo "mongo version $(mongosh --eval 'db.version()') is ready..."
            echo "creating mongo replica set..."
            mongosh --eval 'rs.initiate()'
            mongosh --eval 'rs.conf()'
          }

          replicaset &
          exec mongod --bind_ip_all --replSet=rs0

eslint:
  stage: lint
  image: node:latest
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npx eslint --format=junit src > ../eslint.xml
  artifacts:
    reports:
      junit: eslint.xml

pylint:
  stage: lint
  image: python:latest
  script:
    - apt-get update
    - apt-get install -y gcc libldap-common libldap2-dev libsasl2-dev
    - cd backend
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - uv sync
    - uv run pylint --exit-zero --output-format=junit shrunk tests/*.py > pylint.xml
  artifacts:
    reports:
      junit: backend/pylint.xml

mypy:
  # stage: lint
  when: manual
  image: python:latest
  script:
    - cd backend
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - uv sync
    - uv run mypy --junit-xml=./mypy.xml .
  artifacts:
    reports:
      junit: mypy.xml

ruff-lint:
  stage: lint
  image: python:latest
  script:
    - apt-get update
    - apt-get install -y gcc libldap-common libldap2-dev libsasl2-dev
    - cd backend
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - uv sync
    - uv run ruff check

ruff-format:
  stage: lint
  image: python:latest
  script:
    - apt-get update
    - apt-get install -y gcc libldap-common libldap2-dev libsasl2-dev
    - cd backend
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - uv sync
    - uv run ruff format --check

prettier:
  stage: lint
  image: node:latest
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npx prettier --check .
  
build:
  extends:
    - .buildah
    - .images
  stage: build
  script:
    - buildah build -t "$CI_REGISTRY_IMAGE/${IMAGE}:${CI_COMMIT_SHA}" ${IMAGE}
    - buildah push "$CI_REGISTRY_IMAGE/${IMAGE}:${CI_COMMIT_SHA}"

backend-test:
  extends: .mongo-service
  image:
    name: $CI_REGISTRY_IMAGE/backend:${CI_COMMIT_SHA}
    entrypoint: [""]
  stage: test
  needs:
    - job: build
      parallel:
        matrix:
          - IMAGE: backend
  script:
    - set -a
    - . .env.example
    - set +a
    - export SHRUNK_DB_HOST=mongo
    - export SHRUNK_DB_NAME=shrunk_test
    - export SHRUNK_DB_PORT=27017
    - export SHRUNK_FLASK_TESTING=1
    - export SHRUNK_GOOGLE_SAFEBROWSE_ENABLED=1
    - export SHRUNK_GOOGLE_SAFEBROWSE_API_KEY=$GOOGLE_SAFE_BROWSING_API
    - export SHRUNK_REPLICA_SET_NAME="rs0"
    - pytest --junitxml=pytest.xml backend/tests
  artifacts:
    reports:
      junit: pytest.xml

.accessibility-test:
  extends: .mongo-service
  stage: test
  image: quay.io/podman/stable
  when: on_success
  allow_failure: false
  variables:
    FF_NETWORK_PER_BUILD: true
    SHRUNK_DB_HOST: mongo
    SHRUNK_DB_PORT: 27017
    SHRUNK_DB_NAME: shrunk_test
    SHRUNK_REPLICA_SET_NAME: rs0
    SHRUNK_DEV_LOGINS: 1
    SHRUNK_SEED_DATABASE: 1
    SHRUNK_SECRET_KEY: something_secret
    FLASK_DEBUG: false
    FLASK_APP: shrunk
  before_script:
    - podman login -u "$CI_REGISTRY_USER" --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
  services:
    - *mongo_service
    - name: $CI_REGISTRY_IMAGE/frontend:${CI_COMMIT_SHA}
      alias: frontend
    - name: $CI_REGISTRY_IMAGE/backend:${CI_COMMIT_SHA}
      alias: backend
  script: 
    - mkdir workspace
    - podman build -t pa11y-ci frontend/pa11y-ci
    - podman run --network=${CI_BUILD_NETWORK_NAME} -e PA11Y_URL=frontend:4343 -e PA11Y_THEME=${THEME} -v ${PWD}/workspace:/workspace pa11y-ci
  artifacts:
    when: always
    reports:
      accessibility: workspace/accessibility-${THEME}.json
    paths:
      - workspace/accessibility-${THEME}.json

accessibility-test:
  extends: .accessibility-test
  parallel:
    matrix:
      - THEME: light
      - THEME: dark

promote-build:
  extends:
    - .skopeo
    - .images
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - skopeo copy "docker://$CI_REGISTRY_IMAGE/${IMAGE}:${CI_COMMIT_SHA}"
                  "docker://$CI_REGISTRY_IMAGE/${IMAGE}:${CI_PIPELINE_IID}-build"

promote-prod:
  extends:
    - .skopeo
    - .images
  rules:
  - if: $CI_COMMIT_TAG
  script:
    - skopeo copy "docker://$CI_REGISTRY_IMAGE/${IMAGE}:${CI_COMMIT_SHA}"
                  "docker://$CI_REGISTRY_IMAGE/${IMAGE}:${CI_COMMIT_TAG}"
