services:
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./development.env:/usr/shrunk/backend/.env
      - ./backend:/usr/shrunk/backend
      - backend_venv:/usr/shrunk/backend/.venv
    env_file:
      - ./development.env
    depends_on:
      - mongodb0
      - mongodb1
      - mongodb2
      - frontend
    networks:
      - mongo-net
      - proxy-net

  frontend:
    build:
      context: ./frontend
      target: dev
    env_file:
      - ./development.env
    ports:
      - 3000:3000
    volumes:
      - ./development.env:/usr/shrunk/frontend/.env
      - ./frontend:/usr/shrunk/frontend
    networks:
      - proxy-net

  mongodb0:
    build: ./database
    environment:
      - PRIMARY=1
    networks:
      - mongo-net

  mongodb1:
    build: ./database
    networks:
      - mongo-net

  mongodb2:
    build: ./database
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
    attachable: true
  proxy-net:
    driver: bridge
    attachable: true
