#!/usr/bin/python3

import sys
import shutil
import os
import requests


SHRUNK_DIR = "./shrunk-test-dist"
ZIP_NAME = "repo.zip"
DEV_PATH = "/var/www/outlook/dev"


def download_repo(repo_url: str):
    response = requests.get(repo_url, timeout=10)
    if response.status_code != 200:
        print(f"failed. download status code: {response.status_code}")
    with open(ZIP_NAME, "wb") as file:
        file.write(response.content)
    shutil.unpack_archive(ZIP_NAME, ".")


def move_assets():
    shutil.move(SHRUNK_DIR, DEV_PATH)


def main(repo_url: str):
    if os.path.exists(DEV_PATH + SHRUNK_DIR[1:]):
        shutil.rmtree(DEV_PATH + SHRUNK_DIR[1:])
    if os.path.exists(SHRUNK_DIR):
        shutil.rmtree(SHRUNK_DIR)

    download_repo(repo_url)
    try:
        move_assets()
    except Exception as e:
        print(f"Failed to move assets: {e}")
    os.remove(ZIP_NAME)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(
            "Usage: ./outlook_extension_updater <url of shrunk-test or shrunk-prod zip>"
        )
        print(
            "\tExample: ./outlook_extension_updater https://www.github.com/oss/shrunk-outlook-addin/releases/download/v1.2.3/shrunk-test-dist.zip"
        )
        sys.exit(1)

    url = sys.argv[1]
    main(url)
