AddType application/javascript .js
AddType text/css .css

<VirtualHost *:4343>
    # Spoof as Port 443, shibboleth needs this exact
    ServerName https://shrunk.rutgers.edu:443
    UseCanonicalName On

    ############# Shibboleth config start #############
    # Make sure that the handlers are always available
    <Location /shibboleth>
        Satisfy Any
        Allow from all
    </Location>

    # Aliases for resources used in Shibboleth error templates.
    <IfModule mod_alias.c>
        <Location /shibboleth-sp>
            Satisfy Any
            Allow from all
        </Location>

        Alias /shibboleth-sp/main.css /usr/share/shibboleth/main.css
        # logo.jpg doesn't come with a Shibboleth install, unlike main.css
        # If you would like a logo shown on Shibboleth error pages, you can place
        # one called logo.jpg in /usr/share/shibboleth
        Alias /shibboleth-sp/logo.jpg /usr/share/shibboleth/logo.jpg
    </IfModule>

    # This location requires authentication
    # When the user hits /login, they will be redirect to the CERN SSO page by
    # Shibboleth, then redirected back to /login, via /Shibboleth.sso/ADFS,
    # on successful authentication
    <Location /login>
        AuthType shibboleth
        ShibRequestSetting requireSession 1
        ShibUseHeaders On
        require shib-session
    </Location>

    # Do not proxy pass these
    ProxyPass /shibboleth !
    ProxyPass /shibboleth-sp !
    <Location "/status/">
        ProxyPass !
    </Location>
    #############  Shibboleth config end  #############

    # Exclude /html/ from proxying
    ProxyPass /html/ !

    # Serve React files
    DocumentRoot /var/www
    ErrorDocument 404 /html/index.html
    ErrorDocument 403 /app/403.html
    Alias /app /var/www/html
    <Directory /var/www/html>
        DirectoryIndex index.html
        Require all granted
        Options +Indexes
        AllowOverride All
    </Directory>

    RewriteRule ^/app/(.*)$ /var/www/html/$1 [L]
    <Location /app/>
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^ index.html [L]
    </Location>

    # Proxy settings
    ProxyPreserveHost On
    ProxyErrorOverride On
    RewriteEngine On

    # Proxy /api to Backend
    <Location /api/>
        ProxyPass uwsgi://backend:3050/api/
        ProxyPassReverse uwsgi://backend:3050/api/
    </Location>

    <Location /docs>
        ProxyPass http://docs:3060/
        ProxyPassReverse http://docs:3060/
    </Location>

    # Catch-all: Send everything else to backend
    # (This handles the root redirect and short links)
    ProxyPass / uwsgi://backend:3050/
    ProxyPassReverse / uwsgi://backend:3050/

    ErrorLog /var/log/apache2/error.log
    LogFormat "%h %l %u %t \"%r\" %>s %b" combined
    CustomLog /var/log/apache2/custom.log combined
</VirtualHost>
