apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: oit-eas-macs-shrunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shrunk
      tier: frontend
  template:
    metadata:
      labels:
        app: shrunk
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: ei-quay-quay-quay-enterprise.apps.ocp.ei.rutgers.edu/openshift_oit-eas-macs-shrunk/frontend:latest
          envFrom:
            - configMapRef:
                name: configfile
          volumeMounts:
            - name: logs
              mountPath: "/usr/local/apache2/logs"
          imagePullPolicy: Always
          ports:
            - containerPort: 4343
              protocol: TCP
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: apache-logs
          
