apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: oit-eas-macs-shrunk
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 4343
    protocol: TCP
    targetPort: 4343
  selector:
    app: shrunk
    tier: frontend
  sessionAffinity: None
  type: ClusterIP
