apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: oit-eas-macs-shrunk
spec:
  selector:
    matchLabels:
      app: shrunk
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: shrunk
        tier: backend
    spec:
      containers:
        - name: backend
          image: ei-quay-quay-quay-enterprise.apps.ocp.ei.rutgers.edu/openshift_oit-eas-macs-shrunk/backend:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: configfile
              mountPath: /usr/shrunk/backend/.env
          ports:
          - containerPort: 3050
            protocol: TCP
      volumes:
        - name: configfile
          configMap:
            name: configfile
