apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shrunk-logs
  namespace: oit-eas-macs-shrunk
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: isilon
  volumeMode: Filesystem
