apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: oit-eas-macs-shrunk
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3050
    protocol: TCP
    targetPort: 3050
  selector:
    app: shrunk
    tier: backend
  sessionAffinity: None
  type: ClusterIP
